### PR TITLE
Documentation edited in optical_flow.py file

### PR DESCRIPTION
**Pull request by Zoha-Waheed**
With these enhancements, the script would be more robust, flexible, and easier to understand by other developers.

### CODE REVIEW

**Comment by Zoha-Waheed** [comment]
@hasmithagunda123 before merging PR, please add my name in assignee and respective labels in Pull request.
Thanks alot.

**Comment by Zoha-Waheed** [comment]
@hasmithagunda123 before merging PR, please add my name in assignee and respective labels in Pull request.

**Comment by Zoha-Waheed** [comment]
@hasmithagunda123 please add my name in assignee and respective labels in Pull request. It would not be counted as contribution in Gssoc'24 otherwise.

**Review by hasmithagunda123 — COMMENTED** [review]
merged

**Comment by Zoha-Waheed** [comment]
> merged

Thanks alot.
But still the label of Gssoc is missing in merged PR, kindly add it. It would be a great favour.

**Comment by Zoha-Waheed** [comment]
@hasmithagunda123 please add label of GSSOC, in this PR
Else it wouldnt be counted.

**Pull request merged**
