### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MohanRamSridhar**
I have edited this Readme file based on the previous content.

Issue no: #19

### CODE REVIEW

**Review by hasmithagunda123 — COMMENTED** [review]
add certain images to it

**Comment by 21wh1a6654** [comment]
[Watchful Guardian.docx](https://github.com/hasmithagunda123/ALL_INDIA_HACKATHON/files/15285400/Watchful.Guardian.docx)

**Comment by MohanRamSridhar** [comment]
hey can you please add labels for this PR

**Comment by sanjay-kv** [comment]
@21wh1a6654  please label it + its already mentioned via email to invite me to the repo.

**Pull request merged**
